Name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
	steps: 
		- name: Run git-sizer
      			run: git-sizer --verbose
      		- name: Run echo
      			run: echo "Hello World"